---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongodb-pvc
spec:
  storageClassName: node-mongo-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi