---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-app-load-svc
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      nodePort: 30111
      port: 80
      targetPort: 3000
  selector:
    app: nodejs-app